#undef DEBOUNCE
#define DEBOUNCE 15

#undef TAPPING_TERM
#define TAPPING_TERM 161

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "bVMEP/6a00KX"
#define LAYER_STATE_8BIT

